MODULE TESTS_MOD
    USE FORTRAN_UNIT_TEST_SUITE
    IMPLICIT NONE
    INTEGER :: TEST_EXIT_CODE = 0
END MODULE TESTS_MOD

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_4BYTE()
    USE TESTS_MOD
    INTEGER CODE_STATUS, X, Y
    X = 4
    Y = 4
    CODE_STATUS = PASSED
    CALL ASSERT_EQUAL(X, Y)
    TEST_EXIT_CODE = INTEGER(PASSED == CODE_STATUS)

    IF(.NOT. TEST_EXIT_CODE == 0) THEN
        WRITE(*,*) "ERROR: 'TEST_ASSERT_EQ_PASS_INT_4BYTE' FAILED"
    ENDIF
END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_4BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_8BYTE()
    USE TESTS_MOD
    INTEGER CODE_STATUS
    REAL(8) :: X, Y
    X = 4D0
    Y = 4D0
    CODE_STATUS = PASSED
    CALL ASSERT_EQUAL(X, Y)
    TEST_EXIT_CODE = INTEGER(PASSED == CODE_STATUS)

    IF(.NOT. TEST_EXIT_CODE == 0) THEN
        WRITE(*,*) "ERROR: 'TEST_ASSERT_EQ_PASS_INT_4BYTE' FAILED"
    ENDIF
END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_8BYTE

PROGRAM RUN_TESTS
    USE TESTS_MOD
    IMPLICIT NONE
    CALL TEST_ASSERT_EQ_PASS_INT_4BYTE()
    CALL TEST_ASSERT_EQ_PASS_INT_8BYTE()

    IF(TEST_EXIT_CODE == 0) THEN
        STOP 0
    ELSE
        STOP 1
    ENDIF
END PROGRAM
