SUBROUTINE TEST_FAIL_METHOD
    USE FORTUTF
    CHARACTER(LEN=1) :: PASS

    CALL TAG_TEST("TEST_FAILS_CORRECTLY")

    CALL FAIL

    PASS = TEST_RESULTS(SIZE(TEST_RESULTS))

    IF(FUTF_EXIT_CODE == 1 .AND. PASS == 'F') THEN
        TEST_RESULTS(SIZE(TEST_RESULTS)) = '.'
        FUTF_EXIT_CODE = 0
        FUTF_PASSED = FUTF_PASSED + 1
    ENDIF
END SUBROUTINE TEST_FAIL_METHOD

SUBROUTINE TEST_REGISTER_FAILED
    USE FORTUTF
    CHARACTER(LEN=1) :: PASS

    CALL TAG_TEST("TEST_REGISTER_FAILED")

    CALL REGISTER_FAILED

    IF(FUTF_EXIT_CODE == 1 .AND. PASS == 'F') THEN
        TEST_RESULTS(SIZE(TEST_RESULTS)) = '.'
        FUTF_EXIT_CODE = 0
        FUTF_PASSED = FUTF_PASSED + 1
    ENDIF
END SUBROUTINE TEST_REGISTER_FAILED