SUBROUTINE TEST_FAIL_METHOD
    USE FORTUTF
    CHARACTER(LEN=1) :: PASS
    CHARACTER(LEN=100) :: INFO

    CALL TAG_TEST("TEST_FAILS_CORRECTLY")

    CALL FAIL

    PASS = TEST_RESULTS(SIZE(TEST_RESULTS))

    IF(FUTF_EXIT_CODE == 1 .AND. PASS == 'F') THEN
        TEST_RESULTS(SIZE(TEST_RESULTS)) = '.'
        FUTF_EXIT_CODE = 0
        FUTF_PASSED = FUTF_PASSED + 1
        INFO = "TEST SUCCEEDS: SUCCEEDED AS EXPECTED"
    ELSE
        INFO = "TEST SUCCEEDS: FAILED WHEN SUCCESS EXPECTED"
    ENDIF
    INFO_STRINGS(SIZE(INFO_STRINGS)) = INFO
END SUBROUTINE TEST_FAIL_METHOD

SUBROUTINE TEST_REGISTER_FAILED
    USE FORTUTF
    CHARACTER(LEN=1) :: PASS
    CHARACTER(LEN=100) :: INFO

    CALL TAG_TEST("TEST_REGISTER_FAILED")

    CALL REGISTER_FAILED

    PASS = TEST_RESULTS(SIZE(TEST_RESULTS))

    IF(FUTF_EXIT_CODE == 1 .AND. PASS == 'F') THEN
        TEST_RESULTS(SIZE(TEST_RESULTS)) = '.'
        FUTF_EXIT_CODE = 0
        FUTF_PASSED = FUTF_PASSED + 1
        WRITE(INFO, '(A)') "TEST FAILS: FAILED AS EXPECTED"
    ELSE
        WRITE(INFO, '(A)') "TEST FAILS: SUCCEEDED WHEN FAILURE EXPECTED"
    ENDIF
    INFO_STRINGS = APPEND_CHAR(INFO_STRINGS, INFO, LEN(INFO))
END SUBROUTINE TEST_REGISTER_FAILED