SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_1BYTE
    USE FORTUTF
    INTEGER(1) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_ASSERT_FAIL_INT_IS_CHAR_1BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_1BYTE

SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_2BYTE    
    USE FORTUTF
    INTEGER(2) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_ASSERT_FAIL_INT_IS_CHAR_2BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_2BYTE

SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_4BYTE
    USE FORTUTF
    INTEGER(4) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_ASSERT_FAIL_INT_IS_CHAR_4BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)

    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_4BYTE

SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_8BYTE
    USE FORTUTF
    INTEGER(8) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_ASSERT_FAIL_INT_IS_CHAR_8BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)

    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_ASSERT_FAIL_INT_IS_CHAR_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_CHAR_4BYTE
    USE FORTUTF
    REAL(4) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_FAIL_ASSERT_REAL_IS_CHAR_4BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)

    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_CHAR_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_CHAR_8BYTE
    USE FORTUTF
    REAL(8) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_FAIL_ASSERT_REAL_IS_CHAR_8BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)

    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_CHAR_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_CHAR_4BYTE
    USE FORTUTF
    INTEGER(4) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_CHAR_4BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_CHAR_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_CHAR_8BYTE
    USE FORTUTF
    INTEGER(8) :: X
    
    X = 4
    
    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_CHAR_8BYTE")
    
    CALL ASSERT_IS_CHARACTER(X)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_CHAR_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_CHAR
    USE FORTUTF
    COMPLEX :: X
    
    X = CMPLX(1, 2)
    
    CALL TAG_TEST("TEST_FAIL_ASSERT_COMPLEX_IS_CHAR")
    
    CALL ASSERT_IS_CHARACTER(X)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_CHAR

SUBROUTINE TEST_ASSERT_CHAR_IS_CHAR
    USE FORTUTF
    CHARACTER(LEN=4) :: X
    
    X = "TEST"
    
    CALL TAG_TEST("TEST_ASSERT_CHAR_IS_CHAR")
    
    CALL ASSERT_IS_CHARACTER(X)
    
END SUBROUTINE TEST_ASSERT_CHAR_IS_CHAR
