SUBROUTINE TEST_ASSERT_REAL_IS_REAL_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_REAL_IS_REAL_4BYTE")

    CALL ASSERT_IS_REAL(X)

END SUBROUTINE TEST_ASSERT_REAL_IS_REAL_4BYTE

SUBROUTINE TEST_ASSERT_REAL_IS_REAL_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_REAL_IS_REAL_8BYTE")

    CALL ASSERT_IS_REAL(X)

END SUBROUTINE TEST_ASSERT_REAL_IS_REAL_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE
    USE FORTUTF
    INTEGER(INT_KIND_1BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE
    USE FORTUTF
    INTEGER(INT_KIND_2BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE
    USE FORTUTF
    INTEGER(INT_KIND_4BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE
    USE FORTUTF
    INTEGER(INT_KIND_8BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_REAL
    USE FORTUTF
    COMPLEX :: X

    X = CMPLX(1, 2)

    CALL TAG_TEST("TEST_FAIL_ASSERT_COMPLEX_IS_REAL")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_REAL

SUBROUTINE TEST_FAIL_ASSERT_CHAR_IS_REAL
    USE FORTUTF
    CHARACTER(LEN=4) :: X

    X = "TEST"

    CALL TAG_TEST("TEST_FAIL_ASSERT_CHAR_IS_REAL")

    CALL ASSERT_IS_REAL(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_CHAR_IS_REAL