SUBROUTINE TEST_ASSERT_REAL_IS_REAL_4BYTE
	USE FORTUTF
	REAL(4) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_ASSERT_REAL_IS_REAL_4BYTE")
	
	CALL ASSERT_IS_REAL_REAL_4BYTE(X)
	
END SUBROUTINE TEST_ASSERT_REAL_IS_REAL_4BYTE

SUBROUTINE TEST_ASSERT_REAL_IS_REAL_8BYTE
	USE FORTUTF
	REAL(8) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_ASSERT_REAL_IS_REAL_8BYTE")
	
	CALL ASSERT_IS_REAL_REAL_8BYTE(X)
	
END SUBROUTINE TEST_ASSERT_REAL_IS_REAL_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE
	USE FORTUTF
	INTEGER(1) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE")
	
	CALL ASSERT_IS_REAL_INT_1BYTE(X)
	
	CALL RESET_LAST_TEST_STATUS
	
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_1BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE
	USE FORTUTF
	INTEGER(2) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE")
	
	CALL ASSERT_IS_REAL_INT_2BYTE(X)
	
	CALL RESET_LAST_TEST_STATUS
	
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_2BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE
	USE FORTUTF
	INTEGER(4) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE")
	
	CALL ASSERT_IS_REAL_INT_4BYTE(X)
	
	CALL RESET_LAST_TEST_STATUS
	
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE
	USE FORTUTF
	INTEGER(8) :: X
	
	X = 4
	
	CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE")
	
	CALL ASSERT_IS_REAL_INT_8BYTE(X)
	
	CALL RESET_LAST_TEST_STATUS
	
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_REAL_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IS_COMPLEX
	USE FORTUTF
	COMPLEX :: X
	
	X = CMPLX(1, 2)
	
	CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IS_COMPLEX")
	
	CALL ASSERT_IS_REAL_COMPLEX(X)
	
	CALL RESET_LAST_TEST_STATUS
	
END SUBROUTINE TEST_FAIL_ASSERT_INT_IS_COMPLEX