SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE) :: X, Y
    X = 4
    Y = 4

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_REAL_4BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_4BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE) :: X, Y
    X = 4
    Y = 4

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_REAL_8BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_8BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE) :: X, Y
    X = 4
    Y = 3

    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_REAL_4BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_4BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE) :: X, Y
    X = 4
    Y = 3

    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_REAL_8BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_8BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_ARR_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_REAL_ARR_4BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_ARR_4BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_ARR_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_REAL_ARR_8BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_REAL_ARR_8BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_ARR_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 3, 6, 8/)

    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_REAL_ARR_4BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_ARR_4BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_ARR_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 4, 6, 8/)

    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_REAL_ARR_8BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_REAL_ARR_8BYTE