SUBROUTINE TEST_ASSERT_FALSE
    USE FORTUTF
    LOGICAL X
    X = .FALSE.

    CALL TAG_TEST("TEST_ASSERT_FALSE")

    CALL ASSERT_FALSE(X)

END SUBROUTINE TEST_ASSERT_FALSE

SUBROUTINE TEST_FAIL_ASSERT_FALSE
    USE FORTUTF
    LOGICAL X
    X = .TRUE.

    CALL TAG_TEST("TEST_FAIL_ASSERT_FALSE")

    CALL ASSERT_FALSE(X)

	CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_FALSE

SUBROUTINE TEST_ASSERT_TRUE
    USE FORTUTF
    LOGICAL X
    X = .TRUE.

    CALL TAG_TEST("TEST_ASSERT_TRUE")

    CALL ASSERT_TRUE(X)

END SUBROUTINE TEST_ASSERT_TRUE

SUBROUTINE TEST_FAIL_ASSERT_TRUE
    USE FORTUTF
    LOGICAL X
    X = .FALSE.

    CALL TAG_TEST("TEST_FAIL_ASSERT_TRUE")

    CALL ASSERT_TRUE(X)

	CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_TRUE