SUBROUTINE TEST_EQUAL_LOGICAL
    USE FORTUTF
    LOGICAL :: X, Y
    
    X = .TRUE.
    Y = .TRUE.
    
    CALL TAG_TEST("TEST_EQUAL_LOGICAL")
    
    CALL ASSERT_EQUAL(X, Y)
    
END SUBROUTINE TEST_EQUAL_LOGICAL

SUBROUTINE TEST_FAIL_EQUAL_LOGICAL
    USE FORTUTF
    LOGICAL :: X, Y
    
    X = .TRUE.
    Y = .FALSE.
    
    CALL TAG_TEST("TEST_FAIL_EQUAL_LOGICAL")
    
    CALL ASSERT_EQUAL(X, Y)
    
    CALL RESET_LAST_TEST_STATUS
    
END SUBROUTINE TEST_FAIL_EQUAL_LOGICAL