SUBROUTINE TEST_ASSERT_INT_IN_ARR_1BYTE
    USE FORTUTF

    INTEGER(1), DIMENSION(5) :: ARRAY
    INTEGER(1) :: VAL = 2

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_ASSERT_INT_IN_ARR_1BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

END SUBROUTINE TEST_ASSERT_INT_IN_ARR_1BYTE

SUBROUTINE TEST_ASSERT_INT_IN_ARR_2BYTE
    USE FORTUTF

    INTEGER(2), DIMENSION(5) :: ARRAY
    INTEGER(2) :: VAL = 2

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_ASSERT_INT_IN_ARR_2BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

END SUBROUTINE TEST_ASSERT_INT_IN_ARR_2BYTE

SUBROUTINE TEST_ASSERT_INT_IN_ARR_4BYTE
    USE FORTUTF

    INTEGER(4), DIMENSION(5) :: ARRAY
    INTEGER(4) :: VAL = 2

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_ASSERT_INT_IN_ARR_4BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

END SUBROUTINE TEST_ASSERT_INT_IN_ARR_4BYTE

SUBROUTINE TEST_ASSERT_INT_IN_ARR_8BYTE
    USE FORTUTF

    INTEGER(8), DIMENSION(5) :: ARRAY
    INTEGER(8) :: VAL = 2

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_ASSERT_INT_IN_ARR_8BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

END SUBROUTINE TEST_ASSERT_INT_IN_ARR_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_1BYTE
    USE FORTUTF

    INTEGER(1), DIMENSION(5) :: ARRAY
    INTEGER(1) :: VAL = 12

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IN_ARR_1BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_1BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_2BYTE
    USE FORTUTF

    INTEGER(2), DIMENSION(5) :: ARRAY
    INTEGER(2) :: VAL = 12

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IN_ARR_2BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_2BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_4BYTE
    USE FORTUTF

    INTEGER(4), DIMENSION(5) :: ARRAY
    INTEGER(4) :: VAL = 12

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IN_ARR_4BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_8BYTE
    USE FORTUTF

    INTEGER(8), DIMENSION(5) :: ARRAY
    INTEGER(8) :: VAL = 12

    ARRAY = (/1, 2, 3, 4, 5/)

    CALL TAG_TEST("TEST_FAIL_ASSERT_INT_IN_ARR_8BYTE")

    CALL ASSERT_ARRAY_CONTAINS(ARRAY, VAL)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_INT_IN_ARR_8BYTE