SUBROUTINE TEST_ASSERT_NEQUAL_LOGICAL
    USE FORTUTF
    LOGICAL X, Y

    X = .TRUE.
    Y = .FALSE.

    CALL TAG_TEST("TEST_ASSERT_NEQUAL_LOGICAL")

    CALL ASSERT_NOT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_NEQUAL_LOGICAL

SUBROUTINE TEST_FAIL_ASSERT_NEQUAL_LOGICAL
    USE FORTUTF
    LOGICAL X, Y

    X = .TRUE.
    Y = .TRUE.

    CALL TAG_TEST("TEST_FAIL_ASSERT_NEQUAL_LOGICAL")

    CALL ASSERT_NOT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_NEQUAL_LOGICAL