SUBROUTINE TEST_ALMOST_EQUAL_INT_1BYTE
    USE FORTUTF
    INTEGER(1) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 3
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_ALMOST_EQUAL_INT_1BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

END SUBROUTINE TEST_ALMOST_EQUAL_INT_1BYTE

SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_1BYTE
    USE FORTUTF
    INTEGER(1) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 10
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_FAIL_ALMOST_EQUAL_INT_1BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_1BYTE

SUBROUTINE TEST_ALMOST_EQUAL_INT_2BYTE
    USE FORTUTF
    INTEGER(2) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 3
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_ALMOST_EQUAL_INT_2BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

END SUBROUTINE TEST_ALMOST_EQUAL_INT_2BYTE

SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_2BYTE
    USE FORTUTF
    INTEGER(2) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 20
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_FAIL_ALMOST_EQUAL_INT_2BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_2BYTE

SUBROUTINE TEST_ALMOST_EQUAL_INT_4BYTE
    USE FORTUTF
    INTEGER(4) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 3
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_ALMOST_EQUAL_INT_4BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

END SUBROUTINE TEST_ALMOST_EQUAL_INT_4BYTE

SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_4BYTE
    USE FORTUTF
    INTEGER(4) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 40
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_FAIL_ALMOST_EQUAL_INT_4BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_4BYTE

SUBROUTINE TEST_ALMOST_EQUAL_INT_8BYTE
    USE FORTUTF
    INTEGER(8) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 3
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_ALMOST_EQUAL_INT_8BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

END SUBROUTINE TEST_ALMOST_EQUAL_INT_8BYTE

SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_8BYTE
    USE FORTUTF
    INTEGER(8) :: X, Y
    REAL(8) :: TOLERANCE

    X = 2
    Y = 80
    TOLERANCE = 0.5

    CALL TAG_TEST("TEST_FAIL_ALMOST_EQUAL_INT_8BYTE")

    CALL ASSERT_ALMOST_EQUAL(X, Y, TOLERANCE)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ALMOST_EQUAL_INT_8BYTE


