SUBROUTINE TEST_ASSERT_INT_IS_INT_1BYTE
    USE FORTUTF
    INTEGER(INT_KIND_1BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_INT_IS_INT_1BYTE")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_INT_IS_INT_1BYTE

SUBROUTINE TEST_ASSERT_INT_IS_INT_2BYTE
    USE FORTUTF
    INTEGER(INT_KIND_2BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_INT_IS_INT_2BYTE")

    CALL ASSERT_IS_INT(X)

END SUBROUTINE TEST_ASSERT_INT_IS_INT_2BYTE

SUBROUTINE TEST_ASSERT_INT_IS_INT_4BYTE
    USE FORTUTF
    INTEGER(INT_KIND_4BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_INT_IS_INT_4BYTE")

END SUBROUTINE TEST_ASSERT_INT_IS_INT_4BYTE

SUBROUTINE TEST_ASSERT_INT_IS_INT_8BYTE
    USE FORTUTF
    INTEGER(INT_KIND_8BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_ASSERT_INT_IS_INT_8BYTE")

END SUBROUTINE TEST_ASSERT_INT_IS_INT_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_INT_4BYTE
    USE FORTUTF
    REAL(REAL_KIND_4BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_REAL_IS_INT_4BYTE")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_INT_4BYTE

SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_INT_8BYTE
    USE FORTUTF
    REAL(REAL_KIND_8BYTE) :: X

    X = 4

    CALL TAG_TEST("TEST_FAIL_ASSERT_REAL_IS_INT_8BYTE")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_REAL_IS_INT_8BYTE

SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_INT
    USE FORTUTF
    COMPLEX :: X

    X = CMPLX(1, 2)

    CALL TAG_TEST("TEST_FAIL_ASSERT_COMPLEX_IS_INT")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_COMPLEX_IS_INT

SUBROUTINE TEST_FAIL_ASSERT_CHAR_IS_INT
    USE FORTUTF
    CHARACTER(LEN=4) :: X

    X = "TEST"

    CALL TAG_TEST("TEST_FAIL_ASSERT_CHAR_IS_INT")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_CHAR_IS_INT

SUBROUTINE TEST_FAIL_ASSERT_BOOL_IS_INT
    USE FORTUTF
    LOGICAL :: X

    X = .FALSE.

    CALL TAG_TEST("TEST_FAIL_ASSERT_BOOL_IS_INT")

    CALL ASSERT_IS_INT(X)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_FAIL_ASSERT_BOOL_IS_INT
