SUBROUTINE TEST_ASSERT_EQ_PASS_INT_1BYTE
    USE FORTUTF
    INTEGER(1) :: X, Y
    X = 4
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_1BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_1BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_2BYTE
    USE FORTUTF
    
    INTEGER(2) :: X, Y
    X = 4
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_2BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_2BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_4BYTE
    USE FORTUTF
    
    INTEGER(4) :: X, Y
    X = 4
    Y = 4

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_4BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_4BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_8BYTE
    USE FORTUTF
    
    INTEGER(8) :: X, Y
    X = 4
    Y = 4

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_8BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_8BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_1BYTE
    USE FORTUTF
    INTEGER(1) :: X, Y
    X = 2
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_1BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_1BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_2BYTE
    USE FORTUTF
    INTEGER(2) :: X, Y
    X = 2
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_2BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_2BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_4BYTE
    USE FORTUTF
    INTEGER(4) :: X, Y
    X = 2
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_4BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_4BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_8BYTE
    USE FORTUTF
    INTEGER(1) :: X, Y
    X = 2
    Y = 4
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_8BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_8BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_1BYTE
    USE FORTUTF
    INTEGER(1), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_ARR_1BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_1BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_2BYTE
    USE FORTUTF
    INTEGER(2), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_ARR_2BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_2BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_4BYTE
    USE FORTUTF
    INTEGER(4), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_ARR_4BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_4BYTE

SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_8BYTE
    USE FORTUTF
    INTEGER(8), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/1, 2, 3, 4/)

    CALL TAG_TEST("TEST_ASSERT_EQ_PASS_INT_ARR_8BYTE")

    ! As this test should pass we can leave the
    ! exit code for the framework as is

    CALL ASSERT_EQUAL(X, Y)

END SUBROUTINE TEST_ASSERT_EQ_PASS_INT_ARR_8BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_1BYTE
    USE FORTUTF
    INTEGER(1), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 4, 5, 8/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_ARR_1BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_1BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_2BYTE
    USE FORTUTF
    INTEGER(2), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 4, 5, 8/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_ARR_2BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_2BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_4BYTE
    USE FORTUTF
    INTEGER(4), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 4, 5, 8/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_ARR_4BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_4BYTE

SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_8BYTE
    USE FORTUTF
    INTEGER(8), DIMENSION(4) :: X, Y
    X = (/1, 2, 3, 4/)
    Y = (/2, 4, 5, 8/)
    
    CALL TAG_TEST("TEST_ASSERT_EQ_FAIL_INT_ARR_8BYTE")

    CALL ASSERT_EQUAL(X, Y)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_ASSERT_EQ_FAIL_INT_ARR_8BYTE