MODULE DEMO_FUNCTIONS
    IMPLICIT NONE

    CONTAINS
    
    INTEGER FUNCTION DEMO_FUNC_1(N)
        INTEGER, INTENT(IN) :: N
        DEMO_FUNC_1 = N**2-5
    END FUNCTION

    REAL(8) FUNCTION DEMO_FUNC_2(VAR)
        REAL(8), INTENT(IN) :: VAR
        DEMO_FUNC_2 = (VAR-4)**2
    END FUNCTION
END MODULE
