MODULE DEMO_FUNCTIONS
    IMPLICIT NONE

    INTEGER, PARAMETER :: REAL_KIND_8BYTE = SELECTED_REAL_KIND(15, 307)

    CONTAINS
    
    INTEGER FUNCTION DEMO_FUNC_1(N)
        INTEGER, INTENT(IN) :: N
        DEMO_FUNC_1 = N**2-5
    END FUNCTION

    REAL(REAL_KIND_8BYTE) FUNCTION DEMO_FUNC_2(VAR)
        REAL(REAL_KIND_8BYTE), INTENT(IN) :: VAR
        DEMO_FUNC_2 = (VAR-4)**2
    END FUNCTION

    CHARACTER(LEN=2) FUNCTION DEMO_FUNC_3()
        DEMO_FUNC_3 = "YN"
    END FUNCTION

    COMPLEX FUNCTION DEMO_FUNC_4()
        DEMO_FUNC_4 = (12, 3)
    END FUNCTION
END MODULE
