PROGRAM RUN_DEMO_TESTS
    USE FORTRAN_UNIT_TEST_SUITE
    USE TEST_DEMO_FUNCTIONS

    CALL TEST_DEMO_FUNC_1
    CALL TEST_DEMO_FUNC_2
    CALL TEST_DEMO_FUNC_3
    CALL TEST_DEMO_FUNC_4

    CALL TEST_SUMMARY
END PROGRAM
