MODULE TEST_DEMO_FUNCTIONS
    USE FORTUTF
    USE DEMO_FUNCTIONS

    CONTAINS
    SUBROUTINE TEST_DEMO_FUNC_1
        USE DEMO_FUNCTIONS, ONLY: DEMO_FUNC_1
        CALL TAG_TEST("TEST_DEMO_FUNC_1")
        CALL ASSERT_EQUAL(DEMO_FUNC_1(10), 95)
    END SUBROUTINE
    SUBROUTINE TEST_DEMO_FUNC_2
        USE DEMO_FUNCTIONS, ONLY: DEMO_FUNC_2
        CALL TAG_TEST("TEST_DEMO_FUNC_2")
        CALL ASSERT_EQUAL(DEMO_FUNC_2(11D0), 32D0)
    END SUBROUTINE
    SUBROUTINE TEST_DEMO_FUNC_3
        USE DEMO_FUNCTIONS, ONLY: DEMO_FUNC_3
        CALL TAG_TEST("TEST_DEMO_FUNC_3")
        CALL ASSERT_EQUAL(DEMO_FUNC_3(), "YN")
    END SUBROUTINE
    SUBROUTINE TEST_DEMO_FUNC_4
        USE DEMO_FUNCTIONS, ONLY: DEMO_FUNC_4
        COMPLEX TEMP
        TEMP = (10D0, 1D0)
        CALL TAG_TEST("TEST_DEMO_FUNC_4")
        CALL ASSERT_EQUAL(DEMO_FUNC_4(), TEMP)
    END SUBROUTINE
    SUBROUTINE TEST_DEMO_FUNC_5
        INTEGER, DIMENSION(5) :: INT_1, INT_2
        INT_1 = (/1,2,3,4,5/)
        INT_2 = (/6,7,8,9,10/)
        CALL TAG_TEST("TEST_DEMO_FUNC_5")
        CALL ASSERT_EQUAL(INT_1, INT_2)
    END SUBROUTINE
END MODULE
