! --------------------------------------------------------------------------- !
!                                                                             !
!                           STRING COMPARISON UNIT TESTS                               !
!                                                                             !
! --------------------------------------------------------------------------- !

SUBROUTINE TEST_STRING_SUFFIX_PASS
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: SUFFIX

    TEST_FILE_NAME = "test_file.f90"

    SUFFIX = ".f90"

    CALL STRING_HAS_SUFFIX(TEST_FILE_NAME, SUFFIX)

END SUBROUTINE TEST_STRING_SUFFIX_PASS

SUBROUTINE TEST_STRING_SUFFIX_FAIL
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: SUFFIX

    TEST_FILE_NAME = "test_file.f90"

    SUFFIX = ".cxx"

    CALL STRING_HAS_SUFFIX(TEST_FILE_NAME, SUFFIX)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_STRING_SUFFIX_FAIL

SUBROUTINE TEST_STRING_CONTAINS_PASS
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: CONTENT

    TEST_FILE_NAME = "test_file.f90"

    CONTENT = "file"

    CALL STRING_CONTAINS(TEST_FILE_NAME, CONTENT)

END SUBROUTINE TEST_STRING_CONTAINS_PASS

SUBROUTINE TEST_STRING_CONTAINS_FAIL
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: CONTENT

    TEST_FILE_NAME = "test_file.f90"

    CONTENT = "file"

    CALL STRING_CONTAINS(TEST_FILE_NAME, CONTENT)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_STRING_CONTAINS_FAIL

SUBROUTINE TEST_STRING_PREFIX_PASS
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: PREFIX

    TEST_FILE_NAME = "long_name"

    PREFIX = "long"

    CALL STRING_HAS_PREFIX(TEST_FILE_NAME, PREFIX)

END SUBROUTINE TEST_STRING_PREFIX_PASS

SUBROUTINE TEST_STRING_PREFIX_FAIL
    USE FORTUTF

    CHARACTER(LEN=15) :: TEST_FILE_NAME
    CHARACTER(LEN=4) :: PREFIX

    TEST_FILE_NAME = "long_name"

    PREFIX = "nope"
    CALL STRING_HAS_PREFIX(TEST_FILE_NAME, PREFIX)

    CALL RESET_LAST_TEST_STATUS

END SUBROUTINE TEST_STRING_PREFIX_FAIL
