MODULE FUTS_SPECIALS
    USE FUTS_SUITE, ONLY: TOTAL, PASSED

    IMPLICIT NONE

    CONTAINS

    SUBROUTINE FAIL
        TOTAL = TOTAL + 1
    END SUBROUTINE FAIL

    SUBROUTINE SUCCEED
        TOTAL = TOTAL + 1
        PASSED = PASSED + 1
    END SUBROUTINE SUCCEED

END MODULE FUTS_SPECIALS