MODULE FUTF_SPECIALS
    USE FUTF_SUITE, ONLY: FUTF_TOTAL, FUTF_PASSED, &
        REGISTER_FAILED, REGISTER_PASSED, INFO_STRINGS, APPEND_CHAR

    IMPLICIT NONE

    CONTAINS

    SUBROUTINE FAIL
        CHARACTER(LEN=100) :: INFO
        INFO = "RETURN FAIL"
        CALL REGISTER_FAILED
        INFO_STRINGS = APPEND_CHAR(INFO_STRINGS, INFO, LEN(INFO))
    END SUBROUTINE FAIL

    SUBROUTINE SUCCEED
        CHARACTER(LEN=100) :: INFO
        INFO = "RETURN SUCCEED"
        INFO_STRINGS = APPEND_CHAR(INFO_STRINGS, INFO, LEN(INFO))
        CALL REGISTER_PASSED
    END SUBROUTINE SUCCEED

END MODULE FUTF_SPECIALS