MODULE FUTS_SUITE
    USE FUTS_UTILITIES, ONLY: APPEND_CHAR
    IMPLICIT NONE

    PUBLIC
    INTEGER :: FUTS_PASSED    = 0                   ! Number of FUTS_PASSED Tests
    INTEGER :: FUTS_TOTAL     = 0                   ! FUTS_TOTAL Number of Tests
    INTEGER :: FUTS_EXIT_CODE = 0                   ! Test Suite Exit Code
    CHARACTER(LEN=1), DIMENSION(:), ALLOCATABLE :: TEST_RESULTS

    CHARACTER(LEN=100) :: IDENTIFIER ! String for Test Labels

    CONTAINS

    SUBROUTINE REGISTER_FAILED
        FUTS_TOTAL  = FUTS_TOTAL + 1
        CALL APPEND_CHAR(TEST_RESULTS, 'F')
        FUTS_EXIT_CODE = 1
    END SUBROUTINE

    SUBROUTINE REGISTER_PASSED
        FUTS_PASSED = FUTS_PASSED + 1
        FUTS_TOTAL  = FUTS_TOTAL + 1
        CALL APPEND_CHAR(TEST_RESULTS, '.')
    END SUBROUTINE

    SUBROUTINE TEST_SUMMARY
        CHARACTER(LEN=100) :: RESULT_STR, N_TEST_STR
        WRITE(N_TEST_STR, '(A, i0, A)') "GATHERED ",SIZE(TEST_RESULTS)," TESTS"
        WRITE(*,*) N_TEST_STR
        WRITE(*,*) TEST_RESULTS
        WRITE(RESULT_STR, '(A, i0, A, i0)') REPEAT(" ", 5)//"PASSED: ", FUTS_PASSED, "/", FUTS_TOTAL
        WRITE(*,*) REPEAT("*", 20), " TEST SUMMARY ", REPEAT("*", 20), NEW_LINE('A')
        WRITE(*,*) RESULT_STR, NEW_LINE('A')
        WRITE(*,*) REPEAT("*", 54)
    END SUBROUTINE
END MODULE
