MODULE FUTS_UTILITIES
    IMPLICIT NONE
    CONTAINS
    SUBROUTINE APPEND_CHAR(INPUT_ARRAY, ELEMENT)
        CHARACTER(*), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: INPUT_ARRAY
        CHARACTER(*), INTENT(IN) :: ELEMENT
        CHARACTER, DIMENSION(:), ALLOCATABLE :: TEMP_ARR

        INTEGER :: I, ARR_SIZE

        IF(ALLOCATED(INPUT_ARRAY)) THEN
            ARR_SIZE = SIZE(INPUT_ARRAY)

            ALLOCATE(TEMP_ARR(ARR_SIZE+1))
            DO I=1, ARR_SIZE
                TEMP_ARR(I) = INPUT_ARRAY(I)
            END DO
            TEMP_ARR(ARR_SIZE+1) = ELEMENT

            DEALLOCATE(INPUT_ARRAY)

            CALL MOVE_ALLOC(TEMP_ARR, INPUT_ARRAY)
        ELSE
            ALLOCATE(INPUT_ARRAY(1))
            INPUT_ARRAY(1) = ELEMENT
        ENDIF
    END SUBROUTINE APPEND_CHAR
END MODULE
